lottie/lottie-spec

.github/workflows/pages.yml
.gitignore
docs/editing/schema.md
docs/static/css/lottie-theme.css
mkdocs.yml
tools/theme/main.html

https://lottiefiles.github.io/lottie-spec/

feat: sync UI with lottie.github.io

---

CONTRIBUTING.md

Update contributing guide to explicitly state changes that don't meaningfully change the specification only require one approval.
We should add a tag to mark and track these as well.

Update Approvals Needed Guidelines

---

README.md
mkdocs.yml
schema/root.json

Updates some urls to the new github org.
There is still one left in https://github.com/lottie/lottie-spec/blob/main/2._Scope.md referencing the tests repo. 
I'm not sure what we decided on, are we going to use lottie-spec for rendering examples as well or are we going to use a different repo?

Update links to the new github org

---

docs/editing/extensions.md
docs/editing/schema.md
docs/index.md
docs/specs/shapes.md
docs/static/css/style.css
docs/static/img/ellipse-guide.svg
docs/static/img/rect-guide.svg
mkdocs.yml
tools/latex_markdown.py
tools/lottie_markdown.py
tools/requirements.txt
tools/theme/main.html

Adds wording for shape algorithms. I used BCP 14 words to specify compliance requirements.

Initial wording for shape rendering

---

schema/properties/bezier-keyframe.json

This is how bodymovin exports animated paths.
I'm not sure if other tools export with `s` being the object directly. Ideally it would be nice to have a single way to represent these, though maybe there are technical/pragmatic reasons to support both approaches.

Animated bezier object should be in array

---

schema/assets/image.json

Embedded image is also a string, so would result in both oneOf checks passing and thus triggering a failure.
Instead, conditionally check the format of image string if it is set to be a data url.

Resolve schema failures with embedded images

---

docs/specs/properties.md
docs/static/js/value_editors.js
schema/properties/easing-handle.json

Unlike their X counterpart, Y handle coordinates are not pinned to [0 .. 1].
AE/Bodymovin can export out-of-range Ys, and the expected behavior is for the value to extrapolate beyond the specified keyframe range.

Clarify easing handle Y coord clamping

---

tools/lottie_markdown.py

(Fixed) warning message-
```
DeprecationWarning: Testing an element's truth value will raise
an exception in future versions.  Use specific 'len(elem)' or
'elem is not None' test instead.
```

Fix python truth test deprecation warning

---

docs/specs/properties.md

Must be in ascending frame order
First/last keyframe values are held to start/end
of the animation.

Minor keyframe clarifications

---

.github/workflows/lint.yml
tools/.flake8
tools/lottie_markdown.py
tools/schema-merge.py
tools/schema-validate.py

Adds a workflow to check if the python code follow [PEP8](https://peps.python.org/pep-0008/) code style. And I've fixed existing style issues.

Lint python code

---

schema/properties/bezier-property.json
schema/properties/color-property.json
schema/properties/gradient-property.json
schema/properties/position-property.json
schema/properties/scalar-property.json

* Aligned all schemas so static `k` now has name/description (same as what vector-property had)
* Made position property slottable
* Removed duplicate "sid" for scalar property

Clean up inconsistencies in the property schemas

---

docs/specs/composition.md
schema/composition/animation.json
schema/root.json
tests/validate_animations.test.js
tools/schema-validate.py

Since `v` is already in use for bodymovin version, using `sv` here. Open to alternatives.

Add specification version field

---

docs/specs/properties.md
schema/helpers/transform.json
schema/properties/splittable-position-property.json

Adds `s` on the non-split branch of the splittable position (but not required).
This should not change validation but it will make `s` a recognized property in that case (so the validator will not warn if present)
It also renames splitable -> splittable as the latter seems to be a more common spelling.

Fix some minor things regarding splittable position

---

schema/composition/animation.json

Ensures width/height/framerate are non negative.
Perhaps `fr` should be strictly positive but I didn't want to enforce a minimum framerate (having a framerate of something like 0.5 would be unusual but it still makes sense)

Disallow negative values on some top-level properties

---

docs/static/js/validator.js

Gives a more useful error messages on enum validation errors.

Nicer validation error for constants

---

CONTRIBUTING.md
docs/specs/composition.md

Making sure it's clear that the versioning guideline applies to the specs itself rather than mandating a versioning system for Lottie-related tools

Clarify wording on specs versions

---

docs/index.md
docs/specs/helpers.md
docs/specs/layers.md
docs/specs/properties.md
docs/specs/values.md
mkdocs.yml
tools/lottie_markdown.py
tools/requirements.txt

Using mkdocs-print-site-plugin:
* add a single-page version of the docs under lottie-spec/print_page/
* hide live examples from the consolidated page

Initial single-page docs

---

docs/specs/properties.md
schema/properties/gradient-property.json
tools/lottie_markdown.py
tools/schema_tools/type_info.py

Solves #35 
This does a couple things:
* Expands the `schema_object` block processor to include custom `<tr` elements into the table
* Adds title/description to gradient property `k`
* Adds relevant `k` and `a` rows on the property docs page

Manually show a and k on property docs

---

docs/static/js/validator.js

Adds a custom rule to the validator to fail when `refId` is not a valid asset `id`

Validate layer.refId against layer ids

---

docs/specs/properties.md
docs/static/js/validator.js

Allow at most 2 keyframes with the same t value

---

docs/specs/glossary.md
tools/toc_deflist.py

Fixes a rendering bug and avoids deprecated functions

Fix glossary

---

schema/layers/layer.json
schema/shapes/base-gradient.json

1. Remove `st` as required field on layer. This field was removed in https://github.com/lottie/lottie-spec/pull/53
2. Remove min/max on some gradient scalar properties. Scalar properties are objects and the values are in `k`, so min/max doesn't apply at that level. We would need to reach deeper into the object to properly apply limits.
These were discovered using full strict mode on ajv. We may want to turn this on in our tests, however I was having some issues with cases where the property definition and required were split between if/then/allof etc.

Small schema fixes

---

.gitignore
tools/theme/css/lottie-theme.css

The header UI is broken after the changes from https://github.com/lottie/lottie-spec/pull/80

refactor: improve responsive UI

---

docs/index.md
mkdocs.yml
tools/requirements.txt

I just think it looks better, created an [upstream PR](https://github.com/timvink/mkdocs-print-site-plugin/pull/118) to add this options. Setting this to draft to see if they merge it.

Rename print_page to single-page

---

schema/composition/animation.json
schema/root.json
tools/schema-validate.py

Drafting this to be merged before release.
`$id` will point to the HTML page showing the interactive schema, so people using the schema can easily find the docs.
Draft because we should merge this as one of the last steps before release, however if we package the JSON schema, we should do that with these changes included.

Schema 1.0

---

CONTRIBUTING.md

This sets the minimum total review time for each release to be
Major - 4 weeks (unchanged)
Minor - 2 weeks
Patch - 1 week
Patch has no required requested comment time- these should only contain clean up fixes anyway so request for comments didn't seem neccessary.

Specific timing for minor/patch version releases

---

tests/validate_animations.test.js
tools/lottie_markdown.py
tools/schema-merge.py
tools/schema_tools/type_info.py

Just a couple tweaks to help with code generation

Fix minor issues with the python schema typesystem

---

schema/root.json

We'll need to update the 1.0.1 tag once this is merged

Bump schema version for 1.0.1

---

docs/specs/shapes.md

The expected behavior has been clarified for the case of setting negative values for dash/gap entries, as well as when the sum of all their values is zero.
The behavior is consistent now with the one defined by the SVG standard.
Note:
the results from lottie-web and AE are consistent with this change (in AE only the total sum was tested, it is not possible to set values < 0)
lottie-web 
sample: 
[dash_zeros.json](https://github.com/user-attachments/files/18825871/dash_zeros.json)
tested cases:
`0`
`20 0`
`0 20`
`20 0 20`
`0 20 0`
`20 20 -1`
`0 0`

Handle stroke dash array edge cases.
